### ISSUE TITLE
please could you put this issue in your documentation? I think could help other people

### ISSUE THREAD

**Issue by Skattspa** [enquirer/prompt-confirm#8]
I am a junior programmer. Please, could you explain me why:

```js
var questions = {
  type: 'confirm',
  name: 'myQuestion',
  message: 'Do you want to create a backup?'
};

enquirer.ask(questions)
  .then(function (answers) {
     console.log(answers);
  })
```

This does not work

```js
if (answers.myQuestion) {
  console.log('true condition')
} else {
  console.log('false condition')
}
```

This work

```js
if (!answers.myQuestion){
  console.log('false condition')
} else {
  console.log('true condition')
}
```

What the enquirer is doing with the answers variable? if you `console.log(answer)` you see true/false, but you cant manage that as a boolean.

Thank you in advance!  :)

***

_(edited on 10/20/2017 by @jonschlinkert to add backticks around code and fix code formatting for readability)_

**Comment by jonschlinkert** [comment]
- when using a single prompt (without enquirer), a single answer is returned in the promise. this makes sense since only a single prompt is being run.
- when using enquirer, answers are returned on an object, where the key of each property corresponds to the name of a question, and the value corresponds to the answer of that question.

I'm not sure what you mean about the answer's variable being returned as a boolean, since mentioned enquirer in your example. 

Hopefully the following examples clarify this in more detail.

## Usage as a standalone prompt

```js
var Prompt = require('..');
var prompt = new Prompt({
  name: 'backup',
  message: 'Do you want to create a backup?'
})

prompt.run()
  .then(function(answer) {
    console.log(answer);
    //=> true or false
  });
```

## Usage with enquirer

```js
var Enquirer = require('enquirer');
var enquirer = new Enquirer();

enquirer.register('confirm', require('..'));
enquirer.ask({
  type: 'confirm',
  name: 'backup',
  message: 'Do you want to create a backup?'
})
  .then(function(answers) {
    console.log(answers);
    //=> { backup: true }
    // or
    //=> { backup: false }
  });
```

Does that help? (closing since this is an implementation question, but I'd be happy to continue helping. It would be great if you could ask on stackoverflow too, then I can add this answer there to help other people)
